install.packages("ggplot2")
install.packages("ggalt")
install.packages("viridis")
install.packages("viridisLite")
install.packages("plotrix")
install.packages("ggpubr")
install.packages("tidyverse")
install.packages("broom")
install.packages("AICcmodavg")
install.packages("dplyr")
install.packages("DescTools")
install.packages("scales")
install.packages("ggsci")
install.packages("jmv")
install.packages("knitr")
install.packages("png")
install.packages("patchwork")
install.packages("Hmisc")
install.packages("ggsignif")
install.packages("readr")
install.packages("rstatix")

##---------------Read packages------


library(ggplot2)
library(ggalt)
library(viridis)
library(viridisLite)
library(plotrix)
library(ggpubr)
library(tidyverse)
library(broom)
library(AICcmodavg)
library(dplyr)
library(DescTools)
library(scales)
library(ggsci)
library(jmv)
library(knitr)
library(png)
library(patchwork)
library(Hmisc)
library(ggsignif)
library(readr)
library(rstatix)

